name: SebsPatchVotingPlugin
main: be.seeseemelk.sebspatchvotingplugin.SebsPatchVotingPlugin
version: 1.0.0
commands:
  pvote:
    description: Opens the pvote gui. Type /help pvote to show the help
    usage: |
      /pvote   Opens pvote gui
      /pvote add <name>   Add item
      /pvote remove   Remove item
      /pvote open   Allow voting
      /pvote close   Disallow voting
permissions:
  pvote.*:
    description: Gives access to all commands
    children:
      pvote.basic: true
      pvote.admin: true
  pvote.basic:
    description: Allows you to use /pvote
    default: true
  pvote.admin:
    description: Allows you to modify the pvote screen
    default: op